### ISSUE TITLE
driveOdometry.resetPosition 

### ISSUE THREAD

**Issue by Kateknm** [Riverside-Robotics-5683/Robot2024#4]
Your robot was lost when using Path Planner.  I think the issue is the line below.
DriveSubsytem
Line 298: driveOdometry.resetPosition(**newPose.getRotation()**, new MecanumDriveWheelPositions(), newPose);

The resetPosition method Resets the robot's position on the field. 
This should tell the robot where it is and set that position as the starting position. 

I believe the first argument passed to the resetPosition method should be the angle reported by the robot and the second argument should be the current encoder readings.

Try this changing line 298 to the following: 
driveOdometry.resetPosition(IMUSubsystem.getInstance().getYaw(), getWheelPositions(), newPose);

I could be wrong of course. I'm still learning path planner.

**Comment by N0tACyb0rg** [comment]
I implemented it and it did start working better, but I can't apply a conversion factor less than 1 without it breaking (1/6)

**Comment by Kateknm** [comment]
Check that your constants are correct - kDriveMaxSpeedMPS, kDistanceConversionFactor, kEncoderConversionFactor. Check that what you have in PathPlanner matches the actual robot motion.
